#!/usr/bin/env perl

use warnings;
use strict;

# usage: find . -name '*.py' | xargs pythondefs > JUMPER

while (<>) {
    /(?:def|class) (\w+)/ and print "$1\t$ARGV\t$.\n";

} continue {
    close ARGV if eof;
}

__END__
